#!/bin/bash

userChoice=0

while (true); do
	read -p "Target number: " userChoice

	# invalid input
	if ! [ "$userChoice" -eq "$userChoice" ] 2> /dev/null ; then
	      echo "Sorry, integers only!"
	      continue
	else
		echo "You have picked: $userChoice"
		break;
	fi
done

echo
echo "Renaming Vol $userChoice to $userChoice_***"
echo


#for x in \[Volume\ $userChoice*;
for x in Vol\ $userChoice*;
do
    mv -v "${x}" "${x/Vol\ "$userChoice"\ Ch\ /"$userChoice"_}"
done
